version: "3.9"
services:
  todoapp:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=node
      - MONGO_INITDB_ROOT_PASSWORD=nodeuser
